# Generated by Django 4.2.9 on 2024-02-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_course_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.ImageField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.URLField(blank=True),
        ),
    ]
